import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SearchBar from '@/components/Searchbar';
import '@mantine/dropzone/styles.css';
const inter = Inter({ subsets: ["latin"] });
import '@mantine/tiptap/styles.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <MantineProvider>
          <SearchBar/>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
